#!/usr/bin/env python3
"""Generate API.md: the public surface of the SLiCAP package, one line each.

    python tools/api_inventory.py            # rewrite API.md
    python tools/api_inventory.py --check    # fail when API.md is out of date

Why it exists (Anton, 2026-08-01): the modules are long - SLiCAPmath alone is
3600 lines - but their SURFACE is small: 55 public functions. Reading the
surface takes one screen, reading the file does not, and a helper that already
exists is only found by someone who looks at the surface first. This file is
that surface, so "is there already something that computes X?" is one grep.

Generated, never edited by hand. The docstring's first sentence is the
summary, so it stays true as long as the docstrings do.
"""
from __future__ import annotations

import argparse
import ast
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PACKAGE = ROOT / "SLiCAP"
OUTPUT = ROOT / "API.md"

HEADER = """# SLiCAP API inventory

**Generated by `tools/api_inventory.py` - do not edit.** Regenerate after
adding or renaming a public function:

    python tools/api_inventory.py

Public callables only (a leading underscore means internal). Read this before
adding a helper to a core module: the quantity you need may already have an
implementation, and a second one is a defect, not a feature (CLAUDE.md,
"Preferred workflow for changes").
"""


def _summary(node) -> str:
    """First sentence of the docstring, on one line."""
    text = ast.get_docstring(node) or ""
    text = " ".join(text.split())
    if not text:
        return ""
    for stop in (". ", "; "):
        if stop in text:
            text = text.split(stop)[0]
            break
    return text[:110].rstrip(" .")


def _signature(node) -> str:
    args = node.args
    names = [a.arg for a in args.posonlyargs + args.args]
    defaults = [None] * (len(names) - len(args.defaults)) + list(args.defaults)
    parts = []
    for name, default in zip(names, defaults):
        if default is None:
            parts.append(name)
        else:
            try:
                parts.append(f"{name}={ast.unparse(default)}")
            except Exception:
                parts.append(f"{name}=...")
    if args.vararg:
        parts.append("*" + args.vararg.arg)
    for kwonly, default in zip(args.kwonlyargs, args.kw_defaults):
        parts.append(kwonly.arg if default is None
                     else f"{kwonly.arg}={ast.unparse(default)}")
    if args.kwarg:
        parts.append("**" + args.kwarg.arg)
    return "(" + ", ".join(parts) + ")"


def inventory() -> str:
    lines = [HEADER]
    for path in sorted(PACKAGE.rglob("*.py")):
        if "__pycache__" in str(path) or path.name == "__init__.py":
            continue
        try:
            tree = ast.parse(path.read_text(encoding="utf-8"))
        except SyntaxError:
            continue
        entries = []
        for node in tree.body:
            if not isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef,
                                     ast.ClassDef)):
                continue
            if node.name.startswith("_"):
                continue
            kind = "class" if isinstance(node, ast.ClassDef) else ""
            name = node.name + ("" if kind else _signature(node))
            summary = _summary(node)
            entries.append("- `{0}{1}`{2}".format(
                "class " if kind else "", name,
                " - " + summary if summary else ""))
        if entries:
            lines.append("\n## {0}  ({1} public)\n".format(
                path.relative_to(ROOT), len(entries)))
            lines.extend(entries)
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true",
                        help="exit 1 when API.md differs from the code")
    arguments = parser.parse_args()
    text = inventory()
    if arguments.check:
        current = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
        if current != text:
            print("API.md is out of date - run: python tools/api_inventory.py")
            return 1
        print("API.md is up to date")
        return 0
    OUTPUT.write_text(text, encoding="utf-8")
    print("written: {0} ({1} lines)".format(
        OUTPUT.relative_to(ROOT), len(text.splitlines())))
    return 0


if __name__ == "__main__":
    sys.exit(main())
