# -*- coding: utf-8 -*-
#
# SLiCAP documentation build configuration file, created by
# sphinx-quickstart on Mon Feb  1 11:05:15 2016.
#
# This file is execfile with the current directory set to its
# containing dir.
#
# Last editedJuly 30, 2025
#
# -- General configuration ------------------------------------------------

import os
# Comment the following two lines if SLiCAP is installed!
import sys
sys.path.append("..")
import SLiCAP
_VERSION = SLiCAP.__version__
# Uncomment the next line for updating the manual
#os.system("python Manual.py") # Execute scripts that generate RST snippets 
                              # to be imported in this manual
extensions = ['sphinx.ext.mathjax', 'sphinx.ext.autodoc', 
              'sphinx.ext.autosummary']
math_number_all = False
numfig = True
# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
source_suffix = {'.rst': 'restructuredtext'}

# The master toctree document.
master_doc = 'index'

# General information about the project.
project = u'SLiCAP'
copyright = u'2025, SLiCAP development team'
author = u'Anton Montagne'

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# The short X.Y version.
version = _VERSION
# The full version, including alpha/beta/rc tags.
release = _VERSION

# The language for content autogenerated by Sphinx. 
language = 'en'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
exclude_patterns = ['_build', 'sphinx']

# If true, the current module name will be prepended to all description
# unit titles (such as .. function::).
add_module_names = False

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = False

# -- Options for HTML output ----------------------------------------------

# The theme to use for HTML and HTML Help pages.
html_theme = 'sphinx_rtd_theme'

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

# If not '', a 'Last updated on:' timestamp is inserted at every page bottom,
# using the given strftime format.
html_last_updated_fmt = '%Y, %b %d'

# If false, no module index is generated.
html_domain_indices = False

# If false, no index is generated.
html_use_index = False

# Output file base name for HTML help builder.
htmlhelp_basename = 'SLiCAP_PYTHON'

# -- Options for LaTeX output ---------------------------------------------

latex_elements = {}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (master_doc, 'SLiCAP.tex', u'SLiCAP-programming',
     u'Anton Montagne', 'manual'),
]

# -- Options for manual page output ---------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    (master_doc, 'SLiCAP', u'SLiCAP Documentation',
     [author], 1)
]

# -- Options for Texinfo output -------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (master_doc, 'SLiCAP', u'SLiCAP Documentation',
     author, 'SLiCAP', 'Symbolic Linear Circuit Analysis in Python.',
     'Miscellaneous'),
]
