# This should be ran after documents have been generated
name: Build SLiCAP Package
on: workflow_call
jobs:
  build:
    name: Build distribution
    runs-on: ubuntu-latest

    steps:
      - name: Checkout SLiCAP repository
        uses: actions/checkout@v3
        with:
          repository: SLiCAP/SLiCAP_python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: download html documentation
        uses: actions/download-artifact@v4
        with:
          name: allDocs
          path: SLiCAP/docs
      - name: install build
        run: |
          python -m pip install --upgrade pip
          python -m pip install build
      - name: Build package
        run: python -m build
      - name: Store the distribution packages
        uses: actions/upload-artifact@v4
        with:
          name: python-package-distributions
          path: dist/
